[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "google-api-core"
    "google-api-python-client"
    "google-auth"
    "google-auth-httplib2"
    "google-auth-oauthlib"
    "googleapis-common-protos"
]
build-backend = "setuptools.build_meta"